version: '3'

services:
  blog-service:
    build:
      context: ../blog-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgresql port=5432 user=postgresql password=password dbname=postgresql sslmode=disable timezone=UTC connect_timeout=5"
  authentication-service:
    build:
      context: ./../authentication-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgresql port=5432 user=postgresql password=password dbname=postgresql sslmode=disable timezone=UTC connect_timeout=5"
  postgresql:
    build:
      context: ./../postgresql
    hostname: postgresql
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: password
  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./../frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
